

#################################################################################################################################
#																
# Script Name: Vagrantfile													
# 
# Description: A code to provision 3 VMs for kube local labs 				
# Author: Marcus Costa														
# Email Address: marcus.asc@gmail.com												
# Execution Sample: Just "vagrant up" :)									
# 
#################################################################################################################################


# Some variables

$route_ip = "GWADDR"        # Configure to your environment gateway ip address
$brdg_int = "NICNAME"       # Configure to your environment NIC adapter

Vagrant.configure("2") do |config|
    # Setting up the quantity of VM's will be configured, in this case, 1 to 4.
            # Using the number of VM "i" to compose it VirtualBox name.
            
            config.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/9.json"
            config.vm.define "k8s-cpol" do |kubem|
                kubem.vm.box = "oraclelinux/9"
                # Using the number of VM "i" to compose it hostname
                kubem.vm.hostname = "k8s-cpol"
                kubem.vm.network "public_network", bridge: "#{$brdg_int}" 
                kubem.vm.provider "virtualbox" do |v| 
                    v.memory    = 1500
                    v.cpus      = 2
                    v.name      = "k8s-cpol"
                end
                kubem.vm.provision "shell",
                    run: "always",
                    inline: "ip route del default"    
                kubem.vm.provision "shell",
                    run: "always",
                    inline: "ip route add default via #{$route_ip}"
                    kubem.vm.provision "shell", inline: <<-SHELL
                dnf clean all -y && \
                dnf install epel-release vim wget bash-completion tcpdump curl telnet nmap yum-utils zip unzip -y && \
                yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && \
                dnf remove docker docker-* podman runc && \
                dnf install -y containerd.io && \
                systemctl enable --now containerd && \
                sed -i 's,SELINUX=enforcing,SELINUX=permissive,g' /etc/selinux/config && \
                modprobe overlay && \ 
                modprobe br_netfilter && \
                systemctl disable --now firewalld
                SHELL
                kubem.vm.provision "file", source: "./k8s.sh", destination: "~/k8s.sh"
                kubem.vm.provision "shell", inline: <<-SHELL
                chmod +x k8s.sh && sed -i 's/\r$//' /home/vagrant/k8s.sh && /home/vagrant/k8s.sh
            SHELL
            kubem.vm.provision "shell", inline: <<-SHELL
                dnf install kubeadm-1.28.1 cri-tools kubelet-1.28.1 kubectl-1.28.1 socat conntrack-tools -y
            SHELL
            end 
    # Setting up the quantity of VM's will be configured, in this case, 1 to 4.
            # Using the number of VM "i" to compose it VirtualBox name.
            (1..2).each do |i|            
            config.vm.define "k8s-wol#{i}" do |kubew|
                kubew.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/9.json"
                kubew.vm.box = "oraclelinux/9"
                # Using the number of VM "i" to compose it hostname
                kubew.vm.hostname = "k8s-wol#{i}"
                kubew.vm.network "public_network", bridge: "#{$brdg_int}" 
                kubew.vm.provider "virtualbox" do |v| 
                    v.memory    = 2500
                    v.cpus      = 2
                    v.name      = "k8s-wol#{i}"
                end
                kubew.vm.provision "shell",
                    run: "always",
                    inline: "ip route del default"    
                kubew.vm.provision "shell",
                    run: "always",
                    inline: "ip route add default via #{$route_ip}"
                kubew.vm.provision "shell", inline: <<-SHELL
                dnf clean all -y && \
                dnf install epel-release vim wget bash-completion tcpdump curl telnet nmap yum-utils zip unzip -y && \
                yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && \
                dnf remove docker docker-* podman runc && \
                dnf install -y containerd.io && \
                systemctl enable --now containerd && \
                sed -i 's,SELINUX=enforcing,SELINUX=permissive,g' /etc/selinux/config && \
                modprobe overlay && \ 
                modprobe br_netfilter && \
                systemctl disable --now firewalld
                SHELL
                kubew.vm.provision "file", source: "./k8s.sh", destination: "~/k8s.sh"
                kubew.vm.provision "shell", inline: <<-SHELL
                chmod +x k8s.sh && sed -i 's/\r$//' /home/vagrant/k8s.sh && /home/vagrant/k8s.sh
                SHELL
                kubew.vm.provision "shell", inline: <<-SHELL
                dnf install kubeadm-1.28.1 cri-tools kubelet-1.28.1 kubectl-1.28.1 socat conntrack-tools -y
                SHELL
            end 
        end
        end